Import('qt_env')

env = qt_env.Clone()

env['CPPPATH'] += [
    '$BOOST_PATH',
]

env.AppendUnique(LIBPATH = [
    '..\\shared',
    '..\\bsatk',
    '$ZLIB_PATH/build'
])

env.AppendUnique(LIBS = [
    'mo_shared',
    'bsatk',
    'zlibstatic',
    'kernel32',
    'user32',
    'shell32',
    'advapi32',
    'shlwapi',
    'Version'
])

env.AppendUnique(CPPPATH = [
    '..\\shared',
    '..\\bsatk'
])

#CONFIG(debug, debug|release) {
#  LIBS += -L$$OUT_PWD/../shared/debug -L$$OUT_PWD/../bsatk/debug
#  LIBS += -lDbgHelp
#  DEFINES += DEBUG
#  PRE_TARGETDEPS += $$OUT_PWD/../shared/debug/mo_shared.lib \
#    $$OUT_PWD/../bsatk/debug/bsatk.lib
#} else {
#  LIBS += -L$$OUT_PWD/../shared/release -L$$OUT_PWD/../bsatk/release
#  QMAKE_CXXFLAGS += /GL /GS-
#  QMAKE_LFLAGS += /DEBUG /INCREMENTAL:NO /LTCG /OPT:REF /OPT:ICF
#  PRE_TARGETDEPS += $$OUT_PWD/../shared/release/mo_shared.lib \
#    $$OUT_PWD/../bsatk/release/bsatk.lib
#
#}

env.AppendUnique(CPPDEFINES = [
        '_UNICODE',
        '_CRT_SECURE_NO_WARNINGS',
        '_WINDLL',
        'DEBUG_LOG'
])

env['WARNING_LEVEL'] = 4

lib = env.SharedLibrary('hook', env.Glob('*.cpp') + env.RES('version.rc'))
# FIXME scons bug doesn't provide pdb for executable.
if env['CONFIG'] == 'debug':
    x = env.File('hook.pdb')
    env.Depends(x, lib)
    lib.append(x)
env.Depends(lib, env.Value(env['ENV']['DLLSPATH']))

env.Install(env['INSTALL_PATH'], [
    filter(lambda x: str(x).endswith('.dll') or str(x).endswith('.pdb'), lib),
    env.File('process_blacklist.txt'),
])
