Import('env')

env = env.Clone()

env.RequireLibraries('shared', 'bsatk')

env.AppendUnique(LIBPATH = [
    '${ZLIBPATH}\\build'
])

env.AppendUnique(LIBS = [
    'zlibstatic',
    'kernel32',
    'user32',
    'shell32',
    'advapi32',
    'shlwapi',
    'Version'
])

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

#  QMAKE_CXXFLAGS += /GL /GS-
#  QMAKE_LFLAGS += /DEBUG /INCREMENTAL:NO /LTCG /OPT:REF /OPT:ICF

env.AppendUnique(CPPDEFINES = [
        '_UNICODE',
        '_CRT_SECURE_NO_WARNINGS',
        '_WINDLL',
        'DEBUG_LOG'
])

env['WARNING_LEVEL'] = 4

lib = env.SharedLibrary('hook', env.Glob('*.cpp') + env.RES('version.rc'))
env.InstallModule(lib)
env.Install(env['INSTALL_PATH'], 'process_blacklist.txt')
